import type { World } from '../logic'
import {
  allCubeWorld,
  diagonalWorld,
  emptyOfCubesWorld,
  lineWorld,
  mixedWorld,
  oneSmallCubeWorld,
  proofWorld,
  quantifierWorld,
  starterWorld,
} from './worlds'

export type LevelMode = 'judge' | 'construct' | 'proof'

type BaseLevel = {
  id: number
  chapter: string
  title: string
  topic: string
  mode: LevelMode
  formula: string
  goal: string
  lesson: string
  hint: string
  explanation: string
  world: World
}

export type JudgeLevel = BaseLevel & {
  mode: 'judge'
}

export type ConstructLevel = BaseLevel & {
  mode: 'construct'
  targetTruth: boolean
  candidates: Array<{
    label: string
    world: World
    note: string
  }>
}

export type ProofLevel = BaseLevel & {
  mode: 'proof'
  premises: string[]
  conclusion: string
  proofQuestion: string
  proofOptions: string[]
  correctOption: number
}

export type Level = JudgeLevel | ConstructLevel | ProofLevel

const judge = (level: Omit<JudgeLevel, 'mode'>): JudgeLevel => ({ ...level, mode: 'judge' })
const construct = (level: Omit<ConstructLevel, 'mode'>): ConstructLevel => ({ ...level, mode: 'construct' })
const proof = (level: Omit<ProofLevel, 'mode'>): ProofLevel => ({ ...level, mode: 'proof' })

export const levels: Level[] = [
  judge({
    id: 1,
    chapter: '第 0 章：Tarski 世界入门',
    title: '对象与谓词',
    topic: '原子公式',
    formula: 'Cube(A)',
    goal: '判断 A 是否满足谓词 Cube。',
    lesson: '一阶逻辑从对象开始。A 是个体常元，Cube 是一元谓词，Cube(A) 说的是 A 具有“立方体”这个性质。',
    hint: '先在棋盘上找到 A，再看它的形状。',
    explanation: 'A 的形状是 cube，所以 Cube(A) 为真。',
    world: starterWorld,
  }),
  judge({
    id: 2,
    chapter: '第 0 章：Tarski 世界入门',
    title: '二元关系',
    topic: '关系谓词',
    formula: 'LeftOf(B, C)',
    goal: '理解谓词不只能描述性质，也能描述对象之间的关系。',
    lesson: 'LeftOf(B, C) 是二元关系，意思是 B 在 C 的左边。关系谓词的参数顺序很重要。',
    hint: '比较 B 和 C 的横坐标 x。',
    explanation: 'B 的 x 坐标是 1，C 的 x 坐标是 2，因此 B 在 C 左边。',
    world: starterWorld,
  }),
  judge({
    id: 3,
    chapter: '第 0 章：Tarski 世界入门',
    title: '否定',
    topic: '¬',
    formula: '¬Tet(A)',
    goal: '掌握否定：一个公式不成立时，它的否定成立。',
    lesson: '¬P 表示“不是 P”。如果 Tet(A) 为假，那么 ¬Tet(A) 为真。',
    hint: 'A 是不是四面体？',
    explanation: 'A 是立方体，不是四面体，所以 Tet(A) 为假，¬Tet(A) 为真。',
    world: starterWorld,
  }),
  judge({
    id: 4,
    chapter: '第 0 章：Tarski 世界入门',
    title: '合取',
    topic: '∧',
    formula: 'Cube(A) ∧ Small(A)',
    goal: '理解“并且”：两边都真时，整个公式才真。',
    lesson: 'P ∧ Q 要求 P 和 Q 同时成立。只要有一边为假，合取就是假。',
    hint: '分别检查 A 的形状和大小。',
    explanation: 'A 是立方体，而且 A 是小物体，所以整个合取为真。',
    world: starterWorld,
  }),
  judge({
    id: 5,
    chapter: '第 0 章：Tarski 世界入门',
    title: '析取',
    topic: '∨',
    formula: 'Tet(D) ∨ Large(D)',
    goal: '理解“或者”：至少一边为真，整个公式就真。',
    lesson: 'P ∨ Q 是包容性的“或”。它允许两边都真，也允许只有一边真。',
    hint: 'D 不是四面体，但它的大小呢？',
    explanation: 'Tet(D) 为假，但 Large(D) 为真，所以析取公式仍然为真。',
    world: starterWorld,
  }),
  judge({
    id: 6,
    chapter: '第 0 章：Tarski 世界入门',
    title: '蕴含',
    topic: '→',
    formula: 'Cube(D) → Large(D)',
    goal: '掌握条件句的真值：前件真且后件假时才失败。',
    lesson: 'P → Q 表示如果 P，那么 Q。在真值语义里，只有 P 真而 Q 假时，整个蕴含为假。',
    hint: '先问 D 是不是立方体，再问 D 是不是大的。',
    explanation: 'D 是立方体，也确实是大的，所以 Cube(D) → Large(D) 为真。',
    world: starterWorld,
  }),
  judge({
    id: 7,
    chapter: '第 0 章：Tarski 世界入门',
    title: '等号',
    topic: '=',
    formula: 'A = B',
    goal: '区分“同一个对象”和“属性相似”。',
    lesson: 'A = B 不是说 A 和 B 长得像，而是说两个名字指向同一个对象。',
    hint: '棋盘上 A 和 B 是两个不同标签。',
    explanation: 'A 和 B 是两个不同对象，所以 A = B 为假。',
    world: starterWorld,
  }),
  judge({
    id: 8,
    chapter: '第 0 章：Tarski 世界入门',
    title: '存在量词',
    topic: '∃',
    formula: '∃x Cube(x)',
    goal: '理解“至少有一个”。',
    lesson: '∃x Cube(x) 表示在这个世界里，至少有一个对象 x 是立方体。',
    hint: '只要找到一个立方体，就足够让公式为真。',
    explanation: 'A 和 B 都是立方体，所以存在某个 x 使 Cube(x) 成立。',
    world: quantifierWorld,
  }),
  judge({
    id: 9,
    chapter: '第 0 章：Tarski 世界入门',
    title: '全称量词',
    topic: '∀',
    formula: '∀x Small(x)',
    goal: '理解“所有”：每个对象都必须通过检查。',
    lesson: '∀x Small(x) 表示世界里的每一个对象都是小的。一个反例就能让全称公式为假。',
    hint: '找找有没有 medium 或 large 的对象。',
    explanation: 'B 是 medium，D 和 E 是 large，因此不是所有对象都是 small。',
    world: quantifierWorld,
  }),
  judge({
    id: 10,
    chapter: '第 0 章：Tarski 世界入门',
    title: '量词与条件',
    topic: '∀ + →',
    formula: '∀x (Cube(x) → Small(x))',
    goal: '读懂“所有 P 都是 Q”。',
    lesson: '“所有立方体都是小的”常写成 ∀x (Cube(x) → Small(x))，而不是 ∀x (Cube(x) ∧ Small(x))。',
    hint: '只需要检查那些是 Cube 的对象。',
    explanation: 'B 是 cube 但不是 small，所以这个全称条件句为假。',
    world: quantifierWorld,
  }),
  judge({
    id: 11,
    chapter: '第 0 章：Tarski 世界入门',
    title: '嵌套量词',
    topic: '∃ + ∀',
    formula: '∃x ∀y (x = y ∨ LeftOf(x, y))',
    goal: '理解量词顺序：先找一个 x，再让它面对所有 y。',
    lesson: '这个公式说：存在某个对象 x，它要么就是 y，要么在每个 y 的左边。直觉上，它寻找“最左边”的对象。',
    hint: '找横坐标最小的对象。',
    explanation: 'A 在最左边。对任何 y，y 若是 A 则 A = y，否则 A 在 y 左边。',
    world: proofWorld,
  }),
  judge({
    id: 12,
    chapter: '第 0 章：Tarski 世界入门',
    title: '反例意识',
    topic: '有效性',
    formula: '∃x Cube(x) → ∀x Cube(x)',
    goal: '区分“在本世界为真”和“逻辑上必然为真”。',
    lesson: '一阶逻辑学习的关键跃迁：一个公式在某个世界里可能为真，但不代表它在所有世界里都有效。',
    hint: '当前世界里是否既有立方体，也有非立方体？',
    explanation: '这个世界存在立方体，但并非所有对象都是立方体，所以该公式在当前世界为假。',
    world: proofWorld,
  }),

  judge({
    id: 13,
    chapter: '第 1 章：语法与变量',
    title: '项与公式',
    topic: '语法',
    formula: 'Cube(A)',
    goal: '区分“项”和“公式”。',
    lesson: 'A 本身是项，Cube(A) 才是可以判断真假的公式。谓词把项变成公式。',
    hint: '能判断真假的表达式才是公式。',
    explanation: 'Cube(A) 是完整原子公式，因此能在世界中判真。',
    world: starterWorld,
  }),
  judge({
    id: 14,
    chapter: '第 1 章：语法与变量',
    title: '自由变量',
    topic: '赋值',
    formula: '∃x Cube(x)',
    goal: '看到变量需要量词或赋值来解释。',
    lesson: 'Cube(x) 里的 x 不是某个固定对象；∃x Cube(x) 用存在量词绑定 x，使它成为完整句子。',
    hint: '找一个能赋给 x 的立方体。',
    explanation: 'A 和 D 都可以作为 x 的见证者，所以存在式为真。',
    world: starterWorld,
  }),
  judge({
    id: 15,
    chapter: '第 1 章：语法与变量',
    title: '约束变量',
    topic: '作用域',
    formula: '∀x (Cube(x) → Cube(x))',
    goal: '理解被量词绑定的变量只在作用域内工作。',
    lesson: '∀x 的作用域是括号内公式。这里无论 x 指向哪个对象，Cube(x) → Cube(x) 都成立。',
    hint: 'P → P 永远不会失败。',
    explanation: '对每个对象，前件和后件相同，所以全称公式为真。',
    world: starterWorld,
  }),
  judge({
    id: 16,
    chapter: '第 1 章：语法与变量',
    title: '变量换名',
    topic: 'α 等价',
    formula: '∀y (Cube(y) → Cube(y))',
    goal: '理解约束变量的名字可以安全更换。',
    lesson: '∀x P(x) 和 ∀y P(y) 只要替换不造成捕获，就表达同一件事。',
    hint: '把 y 看成“任意对象”的临时名字。',
    explanation: '这个公式和上一关只是换了约束变量名，真值不变。',
    world: starterWorld,
  }),
  judge({
    id: 17,
    chapter: '第 1 章：语法与变量',
    title: '量词作用域',
    topic: '括号',
    formula: '∀x Cube(x) → Cube(A)',
    goal: '观察括号影响公式结构。',
    lesson: '没有括号时，这个公式读作“如果所有对象都是立方体，那么 A 是立方体”。',
    hint: '前件可能为假，但后件是真的。',
    explanation: '并非所有对象都是立方体，但 A 是立方体；蕴含在当前世界为真。',
    world: starterWorld,
  }),
  judge({
    id: 18,
    chapter: '第 1 章：语法与变量',
    title: '变量遮蔽',
    topic: '嵌套量词',
    formula: '∃x (Cube(x) ∧ ∃x Tet(x))',
    goal: '理解内层量词可以使用同名变量，但会遮蔽外层变量。',
    lesson: '内层 ∃x Tet(x) 的 x 是新的临时名字，不再指外层选中的对象。',
    hint: '分别找一个立方体和一个四面体即可。',
    explanation: '外层 x 可以选 A，内层 x 可以选 B，所以整个公式为真。',
    world: starterWorld,
  }),

  construct({
    id: 19,
    chapter: '第 2 章：模型语义',
    title: '找一个模型',
    topic: '可满足性',
    formula: '∀x Cube(x)',
    goal: '选择一个让公式为真的世界。',
    lesson: '模型语义里，公式真假取决于世界。可满足表示至少有一个世界能让它为真。',
    hint: '全称句要求每个对象都通过检查。',
    explanation: '只有候选 A 中每个对象都是立方体。',
    world: allCubeWorld,
    targetTruth: true,
    candidates: [
      { label: '候选 A', world: allCubeWorld, note: '三个对象全是 Cube。' },
      { label: '候选 B', world: mixedWorld, note: 'B 和 C 不是 Cube。' },
      { label: '候选 C', world: emptyOfCubesWorld, note: '没有 Cube。' },
    ],
  }),
  construct({
    id: 20,
    chapter: '第 2 章：模型语义',
    title: '找反模型',
    topic: '反例',
    formula: '∀x Small(x)',
    goal: '选择一个让公式为假的世界。',
    lesson: '反模型就是让目标公式失败的世界。全称公式只需要一个反例就会失败。',
    hint: '找一个不是 small 的对象。',
    explanation: '候选 B 有 medium 和 large 对象，因此 ∀x Small(x) 为假。',
    world: mixedWorld,
    targetTruth: false,
    candidates: [
      { label: '候选 A', world: oneSmallCubeWorld, note: 'A 是 small，但 B 是 large。' },
      { label: '候选 B', world: mixedWorld, note: 'B 是 medium，C 是 large。' },
      { label: '候选 C', world: { width: 3, height: 2, objects: [{ id: 'A', shape: 'cube', size: 'small', x: 0, y: 0 }] }, note: '唯一对象是 small。' },
    ],
  }),
  construct({
    id: 21,
    chapter: '第 2 章：模型语义',
    title: '存在见证',
    topic: '见证者',
    formula: '∃x (Cube(x) ∧ Small(x))',
    goal: '选择一个让存在式为真的世界。',
    lesson: '存在式为真时，通常能指出一个见证者，也就是让矩阵公式成立的对象。',
    hint: '需要同一个对象既是 Cube 又是 Small。',
    explanation: '候选 A 的 A 是小立方体，提供了见证者。',
    world: oneSmallCubeWorld,
    targetTruth: true,
    candidates: [
      { label: '候选 A', world: oneSmallCubeWorld, note: 'A 同时是 Cube 和 Small。' },
      { label: '候选 B', world: emptyOfCubesWorld, note: '没有立方体。' },
      { label: '候选 C', world: mixedWorld, note: 'A 是小立方体，也能满足。' },
    ],
  }),
  construct({
    id: 22,
    chapter: '第 2 章：模型语义',
    title: '关系模型',
    topic: '三元关系',
    formula: 'Between(B, A, C)',
    goal: '选择一个让 B 位于 A 和 C 之间的世界。',
    lesson: '关系谓词不只看对象属性，还看对象之间的位置结构。',
    hint: 'A、B、C 需要在同一条线上，且 B 在中间。',
    explanation: '候选 A 中 A、B、C 在同一横线上，B 的 x 坐标在 A 和 C 之间。',
    world: lineWorld,
    targetTruth: true,
    candidates: [
      { label: '候选 A', world: lineWorld, note: 'B 在 A 与 C 之间。' },
      { label: '候选 B', world: diagonalWorld, note: 'B 也在 A 与 C 的对角线之间。' },
      { label: '候选 C', world: starterWorld, note: 'B 在 A 和 C 之间，但公式参数顺序同样满足。' },
    ],
  }),
  judge({
    id: 23,
    chapter: '第 2 章：模型语义',
    title: '逻辑蕴涵直觉',
    topic: 'Γ ⊨ φ',
    formula: '∀x Cube(x) → ∃x Cube(x)',
    goal: '感受从全称到存在的语义蕴涵。',
    lesson: '在非空世界里，如果所有对象都是立方体，那么当然存在一个立方体。',
    hint: '当前世界至少有一个对象。',
    explanation: '当前世界非空，且该蕴含没有反例：全称成立时存在式也成立。',
    world: allCubeWorld,
  }),
  judge({
    id: 24,
    chapter: '第 2 章：模型语义',
    title: '可满足不等于有效',
    topic: '有效性',
    formula: '∃x Cube(x)',
    goal: '区分“某些世界真”和“所有世界真”。',
    lesson: '存在立方体是可满足的，但不是逻辑有效的；没有立方体的世界会让它为假。',
    hint: '当前世界只说明它在这里为真。',
    explanation: '当前世界有立方体，所以为真；但 emptyOfCubesWorld 会成为反模型。',
    world: oneSmallCubeWorld,
  }),

  judge({
    id: 25,
    chapter: '第 3 章：量词精通',
    title: '量词否定一',
    topic: '¬∀',
    formula: '¬∀x Cube(x)',
    goal: '掌握“不是所有”就是“存在不是”。',
    lesson: '¬∀x P(x) 等价于 ∃x ¬P(x)。找一个反例即可。',
    hint: '找一个不是 Cube 的对象。',
    explanation: 'B 和 C 都不是 Cube，所以“并非所有对象都是 Cube”为真。',
    world: mixedWorld,
  }),
  judge({
    id: 26,
    chapter: '第 3 章：量词精通',
    title: '量词否定二',
    topic: '¬∃',
    formula: '¬∃x Dodec(x)',
    goal: '掌握“没有”就是“所有都不”。',
    lesson: '¬∃x P(x) 等价于 ∀x ¬P(x)。它说没有任何对象满足 P。',
    hint: '检查是否有十二面体。',
    explanation: 'oneSmallCubeWorld 中没有 dodec，所以公式为真。',
    world: oneSmallCubeWorld,
  }),
  judge({
    id: 27,
    chapter: '第 3 章：量词精通',
    title: '所有 P 都 Q',
    topic: '∀ + →',
    formula: '∀x (Tet(x) → Medium(x))',
    goal: '用条件句表达分类命题。',
    lesson: '“所有四面体都是中等大小”应写成 ∀x (Tet(x) → Medium(x))。',
    hint: '只检查四面体对象。',
    explanation: 'starterWorld 里唯一四面体 B 是 medium，所以公式为真。',
    world: starterWorld,
  }),
  judge({
    id: 28,
    chapter: '第 3 章：量词精通',
    title: '有一个 P 且 Q',
    topic: '∃ + ∧',
    formula: '∃x (Tet(x) ∧ Large(x))',
    goal: '用合取表达“有一个对象同时满足两个性质”。',
    lesson: '存在式里的“且”要求同一个见证者同时满足两个条件。',
    hint: '找大四面体。',
    explanation: 'quantifierWorld 中 E 是 large 的 tet，所以公式为真。',
    world: quantifierWorld,
  }),
  judge({
    id: 29,
    chapter: '第 3 章：量词精通',
    title: '量词顺序一',
    topic: '∀∃',
    formula: '∀x ∃y (x = y)',
    goal: '理解每个对象都可以找到一个对象等于它。',
    lesson: '∀x ∃y 允许 y 随 x 改变。对每个 x，都可以选它自己作为 y。',
    hint: 'y 可以选成当前的 x。',
    explanation: '每个对象都等于自身，所以公式为真。',
    world: quantifierWorld,
  }),
  judge({
    id: 30,
    chapter: '第 3 章：量词精通',
    title: '量词顺序二',
    topic: '∃∀',
    formula: '∃x ∀y (x = y)',
    goal: '看出 ∃∀ 比 ∀∃ 强得多。',
    lesson: '这个公式说存在一个对象等于所有对象；只有单对象世界才可能为真。',
    hint: '当前世界有多个不同对象。',
    explanation: 'A 不等于 B，任何对象都不可能等于所有对象，所以为假。',
    world: quantifierWorld,
  }),
  judge({
    id: 31,
    chapter: '第 3 章：量词精通',
    title: '唯一存在',
    topic: '∃!',
    formula: '∃x (Cube(x) ∧ ∀y (Cube(y) → y = x))',
    goal: '用普通一阶逻辑表达“恰好一个”。',
    lesson: '唯一存在可以拆成：存在一个 x 满足 P，且所有满足 P 的 y 都等于 x。',
    hint: '当前世界有几个立方体？',
    explanation: 'oneSmallCubeWorld 中只有 A 是 Cube，所以唯一存在为真。',
    world: oneSmallCubeWorld,
  }),
  judge({
    id: 32,
    chapter: '第 3 章：量词精通',
    title: '至少两个',
    topic: '不等号思想',
    formula: '∃x ∃y (Cube(x) ∧ Cube(y) ∧ ¬x = y)',
    goal: '用等号和否定表达“至少两个不同对象”。',
    lesson: '当前解析器用 ¬x = y 表示 x 不等于 y。核心思想是找两个不同见证者。',
    hint: '找两个不同的立方体。',
    explanation: 'quantifierWorld 中 A 和 B 都是 Cube，且 A 不等于 B。',
    world: quantifierWorld,
  }),

  proof({
    id: 33,
    chapter: '第 4 章：自然演绎证明',
    title: '合取消去',
    topic: '∧E',
    formula: 'P ∧ Q ⊢ P',
    goal: '从合取命题中取出其中一边。',
    lesson: '自然演绎关注“凭规则推出结论”。∧E 表示从 P ∧ Q 可以推出 P，也可以推出 Q。',
    hint: '看结论是哪一边。',
    explanation: '从 Cube(A) ∧ Small(A) 可直接用 ∧E 得到 Cube(A)。',
    world: starterWorld,
    premises: ['Cube(A) ∧ Small(A)'],
    conclusion: 'Cube(A)',
    proofQuestion: '下一步应该使用哪条规则？',
    proofOptions: ['∧E：从合取中取出左边', '∨I：引入一个析取', '∀E：实例化全称量词'],
    correctOption: 0,
  }),
  proof({
    id: 34,
    chapter: '第 4 章：自然演绎证明',
    title: '合取引入',
    topic: '∧I',
    formula: 'P, Q ⊢ P ∧ Q',
    goal: '把两个已知结论合成一个合取。',
    lesson: '如果你已经证明 P，也已经证明 Q，就可以用 ∧I 得到 P ∧ Q。',
    hint: '前提里已经有两边。',
    explanation: 'Cube(A) 和 Small(A) 都已给出，因此可合取得到 Cube(A) ∧ Small(A)。',
    world: starterWorld,
    premises: ['Cube(A)', 'Small(A)'],
    conclusion: 'Cube(A) ∧ Small(A)',
    proofQuestion: '哪条规则能合成目标公式？',
    proofOptions: ['∧I：合取引入', '¬I：否定引入', '∃E：存在消去'],
    correctOption: 0,
  }),
  proof({
    id: 35,
    chapter: '第 4 章：自然演绎证明',
    title: '蕴含消去',
    topic: '→E',
    formula: 'P → Q, P ⊢ Q',
    goal: '掌握 Modus Ponens。',
    lesson: '→E 又叫肯定前件：如果 P → Q，且 P 成立，那么 Q 成立。',
    hint: '找条件句和它的前件。',
    explanation: '由 Cube(A) → Small(A) 与 Cube(A)，可推出 Small(A)。',
    world: starterWorld,
    premises: ['Cube(A) → Small(A)', 'Cube(A)'],
    conclusion: 'Small(A)',
    proofQuestion: '这一步是哪条经典规则？',
    proofOptions: ['→E：蕴含消去', '∀I：全称引入', '∨E：析取消去'],
    correctOption: 0,
  }),
  proof({
    id: 36,
    chapter: '第 4 章：自然演绎证明',
    title: '析取引入',
    topic: '∨I',
    formula: 'P ⊢ P ∨ Q',
    goal: '理解从一个命题可以推出一个更弱的析取。',
    lesson: '只要 P 已经成立，P ∨ Q 就成立；不需要证明 Q。',
    hint: '析取只要求至少一边成立。',
    explanation: '已知 Cube(A)，因此可以推出 Cube(A) ∨ Tet(A)。',
    world: starterWorld,
    premises: ['Cube(A)'],
    conclusion: 'Cube(A) ∨ Tet(A)',
    proofQuestion: '应该用哪条规则？',
    proofOptions: ['∨I：析取引入', '∧E：合取消去', '→I：蕴含引入'],
    correctOption: 0,
  }),
  proof({
    id: 37,
    chapter: '第 4 章：自然演绎证明',
    title: '全称消去',
    topic: '∀E',
    formula: '∀x P(x) ⊢ P(A)',
    goal: '从所有对象满足 P 推出某个对象满足 P。',
    lesson: '∀E 允许把全称变量替换成任意具体项。',
    hint: '把 x 替换成 A。',
    explanation: '从 ∀x (Cube(x) → Small(x)) 可推出 Cube(A) → Small(A)。',
    world: starterWorld,
    premises: ['∀x (Cube(x) → Small(x))'],
    conclusion: 'Cube(A) → Small(A)',
    proofQuestion: '要从全称句得到 A 的实例，应使用什么？',
    proofOptions: ['∀E：全称消去', '∃I：存在引入', '¬E：否定消去'],
    correctOption: 0,
  }),
  proof({
    id: 38,
    chapter: '第 4 章：自然演绎证明',
    title: '存在引入',
    topic: '∃I',
    formula: 'P(A) ⊢ ∃x P(x)',
    goal: '从具体实例推出存在式。',
    lesson: '如果 A 满足 P，那么当然存在某个 x 满足 P。',
    hint: 'A 就是存在式的见证者。',
    explanation: '由 Cube(A) 可以推出 ∃x Cube(x)。',
    world: starterWorld,
    premises: ['Cube(A)'],
    conclusion: '∃x Cube(x)',
    proofQuestion: '哪条规则把具体对象推广为“存在某个对象”？',
    proofOptions: ['∃I：存在引入', '∀I：全称引入', '→E：蕴含消去'],
    correctOption: 0,
  }),
  proof({
    id: 39,
    chapter: '第 4 章：自然演绎证明',
    title: '蕴含引入',
    topic: '→I',
    formula: '假设 P 推出 Q，则 ⊢ P → Q',
    goal: '理解条件证明。',
    lesson: '要证明 P → Q，可以临时假设 P，然后在该假设下推出 Q，最后解除假设。',
    hint: '条件句证明通常从“假设前件”开始。',
    explanation: '证明 Cube(A) → Cube(A) 时，先假设 Cube(A)，立刻得到 Cube(A)，再引入蕴含。',
    world: starterWorld,
    premises: [],
    conclusion: 'Cube(A) → Cube(A)',
    proofQuestion: '证明蕴含的第一步是什么？',
    proofOptions: ['临时假设 Cube(A)', '先证明 Tet(A)', '直接使用 ∃E'],
    correctOption: 0,
  }),
  proof({
    id: 40,
    chapter: '第 4 章：自然演绎证明',
    title: '反证意识',
    topic: '¬I',
    formula: '假设 P 导出矛盾，则 ⊢ ¬P',
    goal: '理解否定引入的证明形态。',
    lesson: '¬I 的核心是：如果假设 P 会推出矛盾，那么 P 不可能成立。',
    hint: '寻找“假设导致不可能”的结构。',
    explanation: '否定不是凭感觉写下来的，而是通过矛盾来引入。',
    world: starterWorld,
    premises: ['Cube(A)', '¬Cube(A) 会导致矛盾'],
    conclusion: '¬(Cube(A) ∧ ¬Cube(A))',
    proofQuestion: '证明一个否定式常见的策略是什么？',
    proofOptions: ['假设被否定的命题并推出矛盾', '任意替换所有变量', '从存在式推出全称式'],
    correctOption: 0,
  }),

  proof({
    id: 41,
    chapter: '第 5 章：自动推理与范式',
    title: '消除蕴含',
    topic: '→',
    formula: 'P → Q ≡ ¬P ∨ Q',
    goal: '学习自动推理的第一步：去掉蕴含。',
    lesson: '归结法通常先把公式改写成只含 ¬、∨、∧、量词的形式。',
    hint: '如果 P 为假，P → Q 自动为真。',
    explanation: 'P → Q 与 ¬P ∨ Q 真值完全相同。',
    world: starterWorld,
    premises: ['Cube(A) → Small(A)'],
    conclusion: '¬Cube(A) ∨ Small(A)',
    proofQuestion: '哪个改写是正确的？',
    proofOptions: ['¬Cube(A) ∨ Small(A)', 'Cube(A) ∧ Small(A)', 'Small(A) → Cube(A)'],
    correctOption: 0,
  }),
  proof({
    id: 42,
    chapter: '第 5 章：自动推理与范式',
    title: '否定内移',
    topic: 'NNF',
    formula: '¬(P ∧ Q) ≡ ¬P ∨ ¬Q',
    goal: '掌握德摩根律。',
    lesson: '否定范式要求否定只出现在原子公式前。德摩根律是内移否定的关键。',
    hint: '不是“两者都成立”等于“至少有一个不成立”。',
    explanation: '¬(Cube(A) ∧ Small(A)) 等价于 ¬Cube(A) ∨ ¬Small(A)。',
    world: starterWorld,
    premises: ['¬(Cube(A) ∧ Small(A))'],
    conclusion: '¬Cube(A) ∨ ¬Small(A)',
    proofQuestion: '正确的德摩根改写是哪一个？',
    proofOptions: ['¬Cube(A) ∨ ¬Small(A)', '¬Cube(A) ∧ ¬Small(A)', 'Cube(A) ∨ Small(A)'],
    correctOption: 0,
  }),
  proof({
    id: 43,
    chapter: '第 5 章：自动推理与范式',
    title: '量词否定改写',
    topic: 'NNF',
    formula: '¬∀x P(x) ≡ ∃x ¬P(x)',
    goal: '把否定推进量词内部。',
    lesson: '否定穿过量词时，全称和存在会互换。',
    hint: '不是所有对象都有 P，就是有对象没有 P。',
    explanation: '¬∀x Cube(x) 等价于 ∃x ¬Cube(x)。',
    world: mixedWorld,
    premises: ['¬∀x Cube(x)'],
    conclusion: '∃x ¬Cube(x)',
    proofQuestion: '正确改写是哪一个？',
    proofOptions: ['∃x ¬Cube(x)', '∀x ¬Cube(x)', '∃x Cube(x)'],
    correctOption: 0,
  }),
  proof({
    id: 44,
    chapter: '第 5 章：自动推理与范式',
    title: '变量标准化',
    topic: 'Standardize apart',
    formula: '∀x P(x) ∧ ∃x Q(x)',
    goal: '避免不同量词意外共用变量名。',
    lesson: '自动推理会把不同量词绑定的同名变量改开，避免混淆。',
    hint: '内外两个 x 不是同一个变量。',
    explanation: '可改写为 ∀x P(x) ∧ ∃y Q(y)。',
    world: starterWorld,
    premises: ['∀x Cube(x) ∧ ∃x Tet(x)'],
    conclusion: '∀x Cube(x) ∧ ∃y Tet(y)',
    proofQuestion: '哪个改写避免了变量混淆？',
    proofOptions: ['∀x Cube(x) ∧ ∃y Tet(y)', '∀x Cube(y) ∧ ∃x Tet(y)', '∀x ∃x (Cube(x) ∧ Tet(x))'],
    correctOption: 0,
  }),
  proof({
    id: 45,
    chapter: '第 5 章：自动推理与范式',
    title: 'Skolem 化直觉',
    topic: 'Skolem',
    formula: '∃x Cube(x)',
    goal: '理解存在量词可由一个新常元代表。',
    lesson: 'Skolem 化把“存在某个对象”替换为一个新名字，例如 k，并记住 k 是见证者。',
    hint: '新常元不是原世界里的 A，而是证明过程中新引入的名字。',
    explanation: '∃x Cube(x) 可在子句化时用 Cube(k) 表示某个见证者。',
    world: oneSmallCubeWorld,
    premises: ['∃x Cube(x)'],
    conclusion: 'Cube(k)',
    proofQuestion: 'Skolem 常元代表什么？',
    proofOptions: ['一个存在式的见证者', '所有对象', '一个任意谓词'],
    correctOption: 0,
  }),
  proof({
    id: 46,
    chapter: '第 5 章：自动推理与范式',
    title: '合一',
    topic: 'Unification',
    formula: 'P(x) 与 P(A)',
    goal: '理解让两个原子公式变成相同的替换。',
    lesson: '合一寻找变量替换。P(x) 和 P(A) 的最简单合一是 x := A。',
    hint: '只需要决定 x 应该指向谁。',
    explanation: '把 x 替换成 A 后，P(x) 变成 P(A)。',
    world: starterWorld,
    premises: ['Cube(x)', 'Cube(A)'],
    conclusion: 'x := A',
    proofQuestion: '哪个替换能合一 Cube(x) 与 Cube(A)？',
    proofOptions: ['x := A', 'A := x', 'x := Tet'],
    correctOption: 0,
  }),
  proof({
    id: 47,
    chapter: '第 5 章：自动推理与范式',
    title: '归结一步',
    topic: 'Resolution',
    formula: 'P ∨ Q, ¬P ⊢ Q',
    goal: '看到归结如何删除互补文字。',
    lesson: '归结法从两个子句中消去互补文字 P 和 ¬P，保留剩余部分。',
    hint: 'P 与 ¬P 相互抵消。',
    explanation: '由 Cube(A) ∨ Small(A) 和 ¬Cube(A) 可归结出 Small(A)。',
    world: starterWorld,
    premises: ['Cube(A) ∨ Small(A)', '¬Cube(A)'],
    conclusion: 'Small(A)',
    proofQuestion: '归结后剩下什么？',
    proofOptions: ['Small(A)', 'Cube(A)', '¬Small(A)'],
    correctOption: 0,
  }),
  proof({
    id: 48,
    chapter: '第 5 章：自动推理与范式',
    title: '反证式自动证明',
    topic: 'Refutation',
    formula: 'Γ ⊨ φ',
    goal: '理解自动推理常用“加入结论否定并推出矛盾”。',
    lesson: '要证明 Γ ⊨ φ，归结法常检查 Γ ∪ {¬φ} 是否不可满足。',
    hint: '把目标结论先取反。',
    explanation: '若前提加上 ¬φ 导致空子句，就说明 φ 是前提的逻辑后果。',
    world: starterWorld,
    premises: ['Γ', '¬φ'],
    conclusion: '矛盾 / 空子句',
    proofQuestion: '归结反证法证明 Γ ⊨ φ 时加入什么？',
    proofOptions: ['¬φ', 'φ ∧ ¬φ 作为新公理', '所有可能公式'],
    correctOption: 0,
  }),

  judge({
    id: 49,
    chapter: '第 6 章：元逻辑地图',
    title: '可靠性',
    topic: 'Soundness',
    formula: 'Cube(A) → Cube(A)',
    goal: '理解“可证明的都是真的”这句话。',
    lesson: '可靠性说：如果一个公式能被证明系统推出，那么它在语义上有效。证明规则不会制造假结论。',
    hint: 'P → P 是最简单的有效式之一。',
    explanation: '当前世界为真，而且在任何世界中 P → P 都为真。',
    world: starterWorld,
  }),
  proof({
    id: 50,
    chapter: '第 6 章：元逻辑地图',
    title: '完备性',
    topic: 'Completeness',
    formula: '⊨ φ 则 ⊢ φ',
    goal: '了解一阶逻辑最重要的元定理之一。',
    lesson: '完备性说：如果一个公式在所有模型中都真，那么存在形式证明能推出它。',
    hint: '语义真理和语法证明在一阶逻辑里接上了。',
    explanation: '这不是某个世界里的计算，而是关于整个证明系统的定理。',
    world: starterWorld,
    premises: ['φ 在所有模型中为真'],
    conclusion: 'φ 可证明',
    proofQuestion: '完备性连接的是哪两件事？',
    proofOptions: ['语义有效性与形式可证明性', '对象大小与对象形状', '存在量词与坐标轴'],
    correctOption: 0,
  }),
  proof({
    id: 51,
    chapter: '第 6 章：元逻辑地图',
    title: '紧致性',
    topic: 'Compactness',
    formula: '每个有限子集可满足，则整体可满足',
    goal: '建立紧致性定理的轮廓。',
    lesson: '紧致性说：一组一阶句子若每个有限子集都有模型，那么整个集合也有模型。',
    hint: '它把无限问题压回有限片段观察。',
    explanation: '这是元逻辑定理，常用于证明某些结构存在。',
    world: starterWorld,
    premises: ['理论 T 的每个有限子集可满足'],
    conclusion: 'T 可满足',
    proofQuestion: '紧致性关注什么？',
    proofOptions: ['无限理论与有限子集的可满足性关系', '公式字体是否紧凑', '棋盘是否足够小'],
    correctOption: 0,
  }),
  proof({
    id: 52,
    chapter: '第 6 章：元逻辑地图',
    title: '表达力边界',
    topic: 'Limits',
    formula: '一阶逻辑不能表达所有数学性质',
    goal: '知道一阶逻辑强大但有边界。',
    lesson: '一阶逻辑能表达许多局部结构性质，但不能完整刻画所有高阶概念，例如“所有子集”的量化需要二阶逻辑。',
    hint: '一阶量词只量化对象，不量化性质或集合。',
    explanation: '这也是为什么后续会出现二阶逻辑、类型论和模型论。',
    world: starterWorld,
    premises: ['一阶量词只作用于对象'],
    conclusion: '不能直接量化所有性质',
    proofQuestion: '一阶逻辑的量词通常量化什么？',
    proofOptions: ['对象', '谓词本身', '所有证明系统'],
    correctOption: 0,
  }),
]
