import { lplLocalPath, type LplChapter } from './exerciseSchema'

export const lplChapters: LplChapter[] = [
  {
    number: 1,
    title: 'Atomic Sentences',
    focus: 'Names, predicates, atomic formulas, and Tarski-world interpretation.',
    modes: ['tarski', 'textbook'],
    exerciseRefs: [
      {
        id: 'lpl-1-sample',
        chapter: 1,
        exercise: 'sample',
        mode: 'tarski',
        skills: ['atomic formulas', 'predicate interpretation'],
        status: 'placeholder',
        localPath: lplLocalPath(1, 'sample'),
      },
    ],
  },
  {
    number: 2,
    title: 'The Logic of Atomic Sentences',
    focus: 'Validity, consequence, and counterexamples in simple worlds.',
    modes: ['tarski', 'textbook'],
    exerciseRefs: [],
  },
  {
    number: 3,
    title: 'Boolean Connectives',
    focus: 'Negation, conjunction, disjunction, conditionals, and biconditionals.',
    modes: ['boole', 'tarski', 'textbook'],
    exerciseRefs: [],
  },
  {
    number: 4,
    title: 'The Logic of Boolean Connectives',
    focus: 'Truth tables, tautologies, contradictions, equivalence, and consequence.',
    modes: ['boole', 'textbook'],
    exerciseRefs: [],
  },
  {
    number: 5,
    title: 'Methods of Proof for Boolean Logic',
    focus: 'Basic natural deduction rules for propositional logic.',
    modes: ['fitch', 'boole', 'textbook'],
    exerciseRefs: [],
  },
  {
    number: 6,
    title: 'Formal Proofs and Boolean Logic',
    focus: 'Fitch-style proof construction and rule checking.',
    modes: ['fitch', 'textbook'],
    exerciseRefs: [],
  },
  {
    number: 7,
    title: 'Conditionals',
    focus: 'Conditional proof, biconditionals, and proof strategies.',
    modes: ['fitch', 'boole', 'textbook'],
    exerciseRefs: [],
  },
  {
    number: 8,
    title: 'Quantifiers',
    focus: 'Universal and existential quantification in Tarski worlds.',
    modes: ['tarski', 'fitch', 'textbook'],
    exerciseRefs: [],
  },
  {
    number: 9,
    title: 'The Logic of Quantifiers',
    focus: 'Quantifier consequence, countermodels, and nested quantifiers.',
    modes: ['tarski', 'fitch', 'textbook'],
    exerciseRefs: [],
  },
  {
    number: 10,
    title: 'Multiple Quantifiers',
    focus: 'Quantifier order, dependency, uniqueness, and relational structure.',
    modes: ['tarski', 'fitch', 'textbook'],
    exerciseRefs: [],
  },
  {
    number: 11,
    title: 'Methods of Proof for Quantifiers',
    focus: 'Quantifier introduction and elimination rules.',
    modes: ['fitch', 'tarski', 'textbook'],
    exerciseRefs: [],
  },
  {
    number: 12,
    title: 'Formal Proofs and Quantifiers',
    focus: 'Full first-order natural deduction with variable restrictions.',
    modes: ['fitch', 'textbook'],
    exerciseRefs: [],
  },
  {
    number: 13,
    title: 'Identity',
    focus: 'Equality, identity reasoning, uniqueness, and numerical claims.',
    modes: ['tarski', 'fitch', 'textbook'],
    exerciseRefs: [],
  },
  {
    number: 14,
    title: 'Methods of Proof for Identity',
    focus: 'Proof rules and strategies involving equality.',
    modes: ['fitch', 'textbook'],
    exerciseRefs: [],
  },
]
